method: onet
data:
  input_type: pointcloud
  path: /Volumes/Ubuntu/occupancy_networks/data/ShapeNet
  pointcloud_n: 3000
  pointcloud_noise: 0.005
  points_subsample: 2048
model:
  encoder_latent: null
  decoder: sphere
  decoder_kwargs:
    meridian: 96
    latitude: 96
    rad_dim: 7
    interpolation: multi_voxel_sphere
  encoder: multi_voxels_sphere
  encoder_kwargs:
    hidden_dim: 32
    n_channels: 3 
    meridian: 96
    latitude: 96
    rad_dim: 7
  c_dim: 32
  z_dim: 0
training:
  out_dir:  out/pointcloud/dpoc
  batch_size: 32
  model_selection_metric: iou
  model_selection_mode: maximize
test:
  threshold: 0.2
  eval_mesh: true
  eval_pointcloud: false
generation:
  batch_size: 100000
  refine: false
  n_x: 128
  n_z: 1
