method: onet
data:
  classes: ['03001627']
  input_type: voxels
  path: data/ShapeNet
  dim: 3
  points_subsample: 1024
model:
  encoder_latent: null
  decoder: simple_local
  decoder_kwargs:
    sample_mode: bilinear # bilinear / nearest
  encoder: voxel_simple_local
  encoder_kwargs:
    plane_resolution: 32
    plane_type: 'grid'
    unet3d: True
    unet3d_kwargs:
      num_levels: 3
      f_maps: 16
      in_channels: 16
      out_channels: 16
  c_dim: 16
  z_dim: 0
training:
  out_dir:  out/voxels/chair_grid
  batch_size: 64
  model_selection_metric: iou
  model_selection_mode: maximize
  print_every: 10
  visualize_every: 100
  validate_every: 10000
  checkpoint_every: 10000
  backup_every: 10000
  n_workers: 12
  n_workers_val: 12
test:
  threshold: 0.2
  eval_mesh: true
  eval_pointcloud: false
generation:
  vis_n_outputs: 2
  batch_size: 100000
  refine: false
  n_x: 128
  n_z: 1
