method: onet
data:
  input_type: pointcloud
  classes: ['Matterport_input']
  path: /is/rg/avg/speng/project_data/2020/scalable_onet/data
  pointcloud_file: pointcloud.npz
  pointcloud_chamfer_file: pointcloud.npz
  voxels_file: null
  padding: 0.1
  pointcloud_n: 200000
  pointcloud_noise: 0.00
  points_subsample: 2048 
  points_online_sample: False
  psr_method: trim
  psr_trim_factor: 6
model:
  encoder: null
  encoder_latent: null
  c_dim: 0
  z_dim: 0
training:
  out_dir: out/pointcloud/screened_psr_matterport_more_trim
test:
  eval_pointcloud: false
