method: onet
data:
  # classes: ['rooms_05']
  input_type: pointcloud
  path: data/ScanNet
  watertight_path: data/watertight
  points_file: points.npz
  points_iou_file: points.npz
  pointcloud_file: pointcloud.npz
  test_split: val
  # multi_files: 10
  voxels_file: null
  overfit: False
  overfit_num: 0
  padding: 0.1
  pointcloud_n: 10000
  pointcloud_noise: 0.005
  points_subsample: 2048 
  points_online_sample: False
  psr_method: trim
  psr_trim_factor: 4
  psr_add_noise_to_normals: true
model:
  encoder: null
  encoder_latent: null
  c_dim: 0
  z_dim: 0
training:
  out_dir: out/screened_psr_10k_trimmed_w_noise_w_normals
