method: dvr
data:
  dataset_name: DVRShapes
  dataset: DVRShapes
  # classes: ['02691156', '04379243', '03001627', '02958343']
  input_type: pointcloud
  path: data/ScanNet
  watertight_path: Null
  pointcloud_n: 10000
  pointcloud_noise: 0.005
  points_online_sample: False
  points_file: points.npz
  points_iou_file: points.npz
  n_views: 0
  n_training_points: 1024
  test_split: train_small
  val_split: train_small
  train_split: train_small
  depth_extension: png
model:
  encoder_latent: null
  decoder: simple
  encoder_kwargs:
    hidden_dim: 128
  encoder: pointnet_resnet
  c_dim: 128
  z_dim: 0
  lambda_depth: 1.
  lambda_rgb: 0.
  lambda_iou: 0.
  depth_function_kwargs:
    max_points: 2500000
  lambda_normal: 0.05
  depth_function_kwargs:
    schedule_ray_sampling: false
    n_steps: [32, 33]
training:
  out_dir:  out/test_full3
  batch_size: 16
  model_selection_metric: loss_depth_eval
  model_selection_mode: minimize
  print_every: 10
  visualize_every: 10000
  validate_every: 10000
  n_workers: 8
  n_workers_val: 4
  checkpoint_every: 200
test:
  threshold: 0.5
  eval_mesh: true
  eval_pointcloud: false
  model_file: model.pt
generation:
  with_colors: false
  generate_pointcloud: false
