method: onet
data:
  classes: ['rooms_05']
  input_type: pointcloud
  path: data/RoomDataset3
  watertight_path: data/watertight
  pointcloud_n: 10000
  pointcloud_noise: 0.005
  points_subsample: 2048 
  points_online_sample: False
  points_file: points_iou
  points_iou_file: points_iou
  pointcloud_file: pointcloud
  multi_files: 10
  voxels_file: null
  overfit: False
  overfit_num: 0
  padding: 0.1
model:
  encoder_latent: null
  decoder: simple_local
  encoder: pointnet_resnet_local
  encoder_kwargs:
    hidden_dim: 128
    plane_resolution: 64
    plane_type: 'grid'
    unet3d: True
    unet3d_kwargs:
      num_levels: 4
      f_maps: 32
      in_channels: 32
      out_channels: 32
  decoder_kwargs:
    sample_mode: bilinear # bilinear / nearest
  c_dim: 32
  z_dim: 0
training:
  out_dir: out/pointcloud/room/3d_grid_bilinear
  batch_size: 4
  model_selection_metric: iou
  model_selection_mode: maximize
  print_every: 1000
  visualize_every: 10000
  validate_every: 10000
  checkpoint_every: 10000
  backup_every: 20000
test:
  threshold: 0.2
  eval_mesh: true
  eval_pointcloud: false
  model_file: model.pt
generation:
  batch_size: 100000
  vis_n_outputs: 5
  resolution_0: 64
  refine: false
  n_x: 128
  n_z: 1
