method: onet
data:
  input_type: pointcloud
  classes: null
  input_type: pointcloud
  path: /is/rg/avg/speng/project_data/2020/ShapeNet
  watertight_path: data/watertight
  pointcloud_n: 3000
  pointcloud_noise: 0.005
  points_subsample: 2048
  points_online_sample: False
  points_file: points.npz
  points_iou_file: points.npz
  voxels_file: null
  overfit: False
  overfit_num: 0
  padding: 0.1
model:
  encoder_latent: null
  decoder: simple_local_point
  encoder: pointnet_plus_plus
  decoder_kwargs:
    hidden_size: 32
    sample_mode: gaussian
    gaussian_val: 0.2
  c_dim: 32
  z_dim: 0
training:
  out_dir: out/pointcloud/shapenet_pointconv
  batch_size: 24
  model_selection_metric: iou
  model_selection_mode: maximize
  print_every: 100
  visualize_every: 10000
  validate_every: 10000
  checkpoint_every: 2000
  backup_every: 10000
  n_workers: 8
  n_workers_val: 4
test:
  threshold: 0.2
  eval_mesh: true
  eval_pointcloud: false
  model_file: model_best.pt
generation:
  batch_size: 100000
  vis_n_outputs: 2
  refine: false
  n_x: 128
  n_z: 1
