method: onet
data:
  dataset: Shapes3D
  path: data/ShapeNet
  classes: null
  input_type: pointcloud
  train_split: train
  val_split: val
  test_split: test
  dim: 3
  points_file: points.npz
  points_iou_file: points.npz
  points_subsample: 1024
  points_unpackbits: true
  model_file: model.off
  watertight_file: model_watertight.off
  img_folder: img
  img_size: 224 
  img_with_camera: false
  img_augment: false
  n_views: 24
  pointcloud_file: pointcloud.npz
  pointcloud_chamfer_file: pointcloud.npz
  pointcloud_n: 256
  pointcloud_target_n: 1024
  pointcloud_noise: 0.05
  voxels_file: 'model.binvox'
  with_transforms: false
model:
  decoder: simple
  encoder: pointplanenet_resnet
  encoder_latent: null
  decoder_kwargs: {}
  encoder_kwargs:
    hidden_dim: 512 
  encoder_latent_kwargs: {}
  multi_gpu: false
  c_dim: 512
  z_dim: 0
  use_camera: false
  dmc_weight_prior: 10.
training:
  out_dir:  out/default
  batch_size: 64
  model_selection_metric: iou
  model_selection_mode: maximize
  backup_every: 100000
  print_every: 100
  visualize_every: 20000
  checkpoint_every: 10000
  validate_every: 2000
  eval_sample: false
test:
  threshold: 0.5
  eval_mesh: true
  eval_pointcloud: true
  model_file: model_best.pt
generation:
  batch_size: 100000
  refine: false
  n_x: 128
  n_z: 1
preprocessor:
  type: null
  config: ""
  model_file: null
