inherit_from: configs/pointcloud/dpoc.yaml
test:
  model_file: /Users/daniil/ETH/3dvision_project/results/dpoc/5planes_best.pt
model : 
  encoder_kwargs:
    hidden_dim: 32
    n_channels: 5
generation:
  generation_dir: generation_5plane_45_degrees
degrees: 45