method: onet
data:
  input_type: pointcloud
  path: data/RoomDataset6
  #classes: ['03001627']
  watertight_path: data/watertight
  pointcloud_n: 10000
  pointcloud_noise: 0.0
  points_subsample: 2048 
  points_online_sample: False
  points_file: points_iou
  points_iou_file: points_iou
  pointcloud_file: pointcloud
  #points_unpackbits: false
  multi_files: 10
  voxels_file: null
  overfit: False
  overfit_num: 0
  padding: 0.1
model:
  decoder: simple_conv
  decoder_kwargs:
    n_conv_layer: 4
    plane_type: ['grid']
  encoder: null
  encoder_latent: pointnet_conv
  encoder_latent_kwargs:
    hidden_dim: 128
    plane_resolution: 32
    n_conv_layer: 4
    plane_type: ['grid'] #['xz', 'xy', 'yz']
  c_dim: 0
  z_dim: 32
training:
  out_dir: out/generative2/voxel2
  batch_size: 32
  model_selection_metric: loss
  model_selection_mode: minimize
  print_every: 10
  visualize_every: 10000
  validate_every: 10000
  checkpoint_every: 500
  backup_every: 10000
  n_workers: 8
  n_workers_val: 4
  beta_vae: 1.
test:
  threshold: 0.2
  eval_mesh: true
  eval_pointcloud: false
  model_file: model.pt
generation:
  batch_size: 100000
  vis_n_outputs: 2
  resolution_0: 32
  upsampling_steps: 2
  refine: false
  n_x: 128
  n_z: 1
  use_sampling: True
